CREATE TABLE IF NOT EXISTS bpm_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    user_name VARCHAR(255),
    real_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(50),
    position_code VARCHAR(50),
    position_name VARCHAR(255),
    gender INT,
    avatar VARCHAR(500),
    birth_date TIMESTAMP,
    company_id BIGINT,
    dept_id BIGINT,
    tenant_id VARCHAR(50),
    password VARCHAR(255),
    entry_time TIMESTAMP,
    leave_time TIMESTAMP,
    hire_status INT,
    source VARCHAR(50),
    lock_status INT,
    valid_state INT DEFAULT 1,
    operator_id BIGINT,
    operator_name VARCHAR(255),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);
